### PR TITLE
hugo installer

### PR DESCRIPTION
**Pull request by ryanburnette**
- [x] macOS
- [x] Linux
- [ ] Windows

### CODE REVIEW

**Comment by ryanburnette** [comment]
I copied the caddy installer, but hugo works on windows too.

**Comment by solderjs** [comment]
Hugo releases look sane: https://github.com/gohugoio/hugo/releases

Does your Hugo installer work? If not, can you test following the `ripgrep` example instead?

(the only difference is that Caddy does NOT use subfolders where as ripgrep does)

**Comment by ryanburnette** [comment]
- [x] macOS
- [x] Linux
- [ ] Windows

**Comment by solderjs** [comment]
I used the new caddy as a template for this

When you add something new that's a single file type of thing like `rg`, `caddy`, `hugo`, `gitea`, etc, copy from the caddy template and replace `pkg_get_current_version` with a function that properly parses the version.

If it's something more like `node`, `go`, `flutter`, that has a full environment with it, use `node` as a template and likewise replace the `pkg_get_current_version`.

**Pull request closed without merging**
