### PR TITLE
WIP: caddy installer

### PR DESCRIPTION
**Pull request by ryanburnette**
> Work in progress. Do not merge.

Working on a caddy installer.

### CODE REVIEW

**Comment by ryanburnette** [comment]
@solderjs How do you suggest we test it? And by test I mean manually. It would be cool to have an automated test that used Vagrant though.

**Comment by solderjs** [comment]
I like the idea of automating, for sure.

**Comment by solderjs** [comment]
Note: you didn't rename from `rg.bash` to `caddy.bash`

**Comment by solderjs** [comment]
...so I'd suggest first testing locally :)

I'll make a way to test in-repo as well.

**Comment by ryanburnette** [comment]
You merged already?

**Pull request merged**
