### PR TITLE
gitea installer

### PR DESCRIPTION
**Pull request by ryanburnette**
- [ ] macOS
- [ ] Linux
- [ ] Windows

### CODE REVIEW

**Comment by ryanburnette** [comment]
needs windows installer

**Comment by ryanburnette** [comment]
Both of my current PRs need some help

```
# ryanburnette @ ryans-mbp in ~/Development/webinstall.dev-packages on git:gitea o [9:18:19] 
$ curl http://localhost:3000/gitea | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1841  100  1841    0     0  92050      0 --:--:-- --:--:-- --:--:-- 92050
Could not find gitea v0.0.0

# ryanburnette @ ryans-mbp in ~/Development/webinstall.dev-packages on git:gitea o [9:32:26] C:1
$ curl http://localhost:3000/gitea@latest | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1841  100  1841    0     0   179k      0 --:--:-- --:--:-- --:--:--  179k
Could not find gitea v0.0.0

# ryanburnette @ ryans-mbp in ~/Development/webinstall.dev-packages on git:gitea o [9:32:38] C:1
$ 

```

**Comment by solderjs** [comment]
This was an issue with using bare `.xz` and `.exe`. Support for bare xz compressed files is in master, awaiting testing.

**Comment by ryanburnette** [comment]
Fail on macOS

```
❯ curl http://localhost:3000/gitea | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1841  100  1841    0     0   178k      0 --:--:-- --:--:-- --:--:--  199k
Could not find gitea v0.0.0
```

This was tested using the `master` branch of webinstall.dev, and `ryanburnette/gitea` branch of packages/installers.

**Comment by solderjs** [comment]
Check out `hugo` and `caddy` and see if you can get gitea working from those.

Despite having just added gitea, I'd be happy to trash it in favor of the new approach.

**Pull request closed without merging**
