### PR TITLE
exe added to format array

### PR DESCRIPTION
**Pull request by Akshansh99**
I've correctly formatted the code and avoided any duplication of lines.

### CODE REVIEW

**Comment by solderjs** [comment]
That actually doesn't follow the same spacing as the others - again, I'd highly recommend VSCode or `vim` + Prettier. It will make it much more pleasant for you to work with open source projects in the future.

Check out https://webinstall.dev/prettier/

The VSCode plugin is easy to find in their search and I'll be adding http://webinstall.dev/vim-prettier soon https://github.com/webinstall/packages/issues/86

However, this is good enough to accept.

Thanks for contributing.

**Comment by solderjs** [comment]
Oh, I see that you updated the spacing, thanks.

Do you know about `git rebase -i master`? You can `squash` extra commits away so that the merge is very clean and then `git push --force <REMOTE> <BRANCH>` to overwrite the previous commit.

I'll still accept this as-is, but if you'd like to try that, this would be a very simple and perfect opportunity to do so.

**Comment by Akshansh99** [comment]
No I didn't knew about these git commands. I'll do these. Thanks for the guidance!

**Comment by solderjs** [comment]
Hmmm... it looks like that didn't quite work as expected. It should have squashed into just one single commit, but now there are 4 commits:

https://github.com/webinstall/packages/pull/91/commits

Try `git rebase -i 4` instead of `git rebase -i master`. It may be that your master was based on those extra commits.

**Comment by Akshansh99** [comment]
I've squashed all the extra commits into a single commit :

https://github.com/webinstall/packages/pull/91/commits

**Comment by solderjs** [comment]
Perfect. Thanks.

**Pull request merged**
