### PR TITLE
agregate the download source #63

### PR DESCRIPTION
**Pull request by yollotltamayo**
This is my first PR. Let me know if you have any feedback!

### CODE REVIEW

**Comment by solderjs** [comment]
Interesting. I myself do not know what `\e]8;;` and `\a` are. What are they?

And this may sound like a stupid question... but is that compatible across Terminal.app, iTerm, GnomeTerminal (?), WSL, ssh, bash, zsh, and fish?

And if there's anywhere that it isn't compatible, will it safely be ignored and display _The Right Thing™_ anyway?

If it is overwhelmingly supported across platforms (Mac, Linux, WSL) and architectures, I'd like to have some comments that explain those pieces such that others encountering it understand the incantation. 🧙‍♂️ 

And welcome to to the wide world of Git and Pull and Merge Requests! :)

**Comment by solderjs** [comment]
In my brief testing, it looks like it adds a dashed underline in `fish` and `zsh` on iTerm, but `bash` cannot understand it:

```bash
echo -e "\e]8;;https://example.com\ahttps://example.com\e]8;;\a"
\e]8;;https://example.comhttps://example.com\e]8;;
```

Since `bash` is the most widely used shell, I think it'll be best to drop that. If you'd like to add some other form of decoration that is cross-shell and cross-terminal compatible, I'd be fine with that (again, with comments).

**Comment by solderjs** [comment]
Hmmm... actually, it may just be that `echo -e` doesn't understand it in bash. On a hunch I tried `printf` and I think it's doing the trick:

```
echo $SHELL
/bin/bash

printf "\e]8;;https://example.com\ahttps://example.com\e]8;;\a\n"
https://example.com
```

I also tried it in `Terminal.app` and it is simply ignoring the formatting.

The behavior seems to not change over SSH.

I would imagine that any recent version of WSL should print properly... but that would be good to test.

**Comment by yollotltamayo** [comment]
Hello ,`\e]8;;` and  `\a` are part of a  feature in VTE's based terminals(you can check it out [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) for the full answer) ,also in the same page the apps and terminal that support the incantation :mage_man: are specified .

The problem of showing the link may be solve by the terminal itself , most terminals auto detect the URL , the above feature `'\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'` is used for displaying links in specified words, so a simply `echo` will solve the link problem , (I would have liked to know this before , my bad), also thank you for the prompt answer  ,right now i'm finishing the new PR.

**Comment by solderjs** [comment]
Thanks.

Also: `git pull --rebase https://github.com/webinstall/packages master` and then `git push --force orogin download_source` if you don't mind.

**Comment by solderjs** [comment]
Doesn't need comments for the plain echo, just wanted comments if you were going to keep in the `\e]8;;`.

However, not a big. Comments can be left. I'll approve and squash merge.

**Comment by yollotltamayo** [comment]
Just made the new PR ,i think now it is fine.

**Comment by solderjs** [comment]
P.S. Have you checked out https://webinstall.dev?

Lot's of very simple, easy to use developer tools:

- https://webinstall.dev/rg
- https://webinstall.dev/curlie
- https://webinstall.dev/bat
- https://webinstall.dev/myip
- https://webinstall.dev/ssh-pubkey

**Comment by solderjs** [comment]
Thanks for contributing. :)

**Pull request merged**
